version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/workspace

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "requirements-dev.txt" }}-v1

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements-dev.txt" }}-v1

      - run:
          name: check format
          command: |
            . venv/bin/activate
            black --check

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v

      - store_artifacts:
          path: test-reports
          destination: test-reports
